package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-glinux-aarch64/jdk8u321/2141/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, December 15, 2021 7:30:49 PM GMT
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
  	 * The value representing ID_ASSIGNMENT_POLICY_ID.
  	 */
  public static final int value = (int)(19L);
}
